# Code generated by Claude AI

"""
De novo promoter scanner for Reg-Seq data.

Scans all (experiment, promoter) pairs and flags cases where a single mutation
causes a large expression shift in an otherwise silent promoter.

Notebook usage:
--------------
    import pandas as pd
    import numpy as np
    from denovo_scanner import build_wt_dict, run_scan, save_outputs, load_df_map

    df_map  = load_df_map("../../reg-seq_env/data/metadata/barcode_map.csv")
    wt_dict = build_wt_dict("../../reg-seq_env/data/metadata/wt_sequences.csv")

    indices = [np.str_('1-1'), np.str_('1-2'), ...]   # your list as-is

    df_results = run_scan(
        indices=indices,
        df_map=df_map,
        wt_dict=wt_dict,
        data_dir="../../reg-seq_env/data/extracted_barcodes",
        noise_a=8.0,
        mi_z=3.0,
        es_k=2.0,
    )

    candidates = save_outputs(
        df_results, indices, df_map, wt_dict,
        data_dir="../../reg-seq_env/data/extracted_barcodes",
        noise_a=8.0, mi_z=3.0, es_k=2.0,
        output_dir="./denovo_results",
    )
"""

import warnings
from glob import glob
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numba import njit

warnings.filterwarnings("ignore")


# ---------------------------------------------------------------------------
# Numba kernels (your implementations, unmodified)
# ---------------------------------------------------------------------------

@njit
def compare_string_bytes_equal(s1, s2):
    n = len(s1)
    result = np.empty(n, dtype=np.int64)
    for i in range(n):
        result[i] = 1 if s1[i] == s2[i] else 0
    return result


@njit
def safe_log2(x):
    return np.log(x) / np.log(2.0)


@njit
def mi_from_joint_2x2(joint):
    """MI from a (2,2) joint probability matrix."""
    px0 = joint[0, 0] + joint[0, 1]
    px1 = joint[1, 0] + joint[1, 1]
    pz0 = joint[0, 0] + joint[1, 0]
    pz1 = joint[0, 1] + joint[1, 1]
    mi = 0.0
    for x in range(2):
        for z in range(2):
            p = joint[x, z]
            if p <= 0.0:
                continue
            px = px0 if x == 0 else px1
            pz = pz0 if z == 0 else pz1
            if px <= 0.0 or pz <= 0.0:
                continue
            mi += p * safe_log2(p / (px * pz))
    return mi


@njit
def h2(p):
    if p <= 0.0 or p >= 1.0:
        return 0.0
    return -p * safe_log2(p) - (1.0 - p) * safe_log2(1.0 - p)


@njit
def accumulate_shifts(int_seq, is_mut, exp_diff, ex_shift_arr):
    num_variants, seq_len = int_seq.shape
    for i in range(num_variants):
        for j in range(seq_len):
            base = int_seq[i, j]
            ex_shift_arr[j, base] += exp_diff[i] * is_mut[i, j]


# ---------------------------------------------------------------------------
# DNA encoding
# ---------------------------------------------------------------------------

DNA_MAPPING = np.zeros(256, dtype=np.uint8)
DNA_MAPPING[ord('A')] = 0
DNA_MAPPING[ord('C')] = 1
DNA_MAPPING[ord('G')] = 2
DNA_MAPPING[ord('T')] = 3


def batch_dna_to_int(sequences, mapping=DNA_MAPPING):
    n = len(sequences[0])
    seq_arr = np.empty((len(sequences), n), dtype=np.uint8)
    for i, seq in enumerate(sequences):
        seq_arr[i, :] = np.frombuffer(seq.encode('ascii'), dtype=np.uint8)
    return mapping[seq_arr]


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def build_wt_dict(wt_csv_path: str) -> dict:
    """
    Load WT sequences from CSV.
    Expects columns 'promoter' and 'promoter_seq'.
    """
    df = pd.read_csv(wt_csv_path)[['promoter_seq', 'promoter']]
    return dict(zip(df['promoter'].values, df['promoter_seq'].values))


def load_df_map(map_path: str) -> pd.DataFrame:
    return pd.read_csv(map_path)


def get_counts(ind, df_map: pd.DataFrame, data_dir: str = ".") -> pd.DataFrame:
    """
    Load DNA and RNA barcode count files for experiment index `ind`.
    Left-merge DNA <- RNA so zero-RNA barcodes are kept (ct_1 = 0).
    Inner-merge with df_map to keep only mapped barcodes.
    """
    files_dna = glob(f"{data_dir}/{ind}*DNA*.txt")
    files_rna = glob(f"{data_dir}/{ind}*RNA*.txt")
    if not files_dna or not files_rna:
        raise FileNotFoundError(f"No files found for index {ind} in {data_dir}")

    df_dna = pd.read_csv(files_dna[0], names=["ct_0", "barcode"], sep=r"\s+")
    df_rna = pd.read_csv(files_rna[0], names=["ct_1", "barcode"], sep=r"\s+")

    df = df_dna.merge(df_rna, on="barcode", how="left").fillna(0)
    df = df.merge(df_map, on="barcode", how="inner")
    return df


# ---------------------------------------------------------------------------
# MI footprint (your implementation)
# ---------------------------------------------------------------------------

def _transform_counts(c, transform="sqrt"):
    c = c.astype(np.float64)
    if transform == "raw":   return c
    if transform == "sqrt":  return np.sqrt(c)
    if transform == "log1p": return np.log1p(c)
    if transform.startswith("pow:"):
        return np.power(c, float(transform.split(":")[1]))
    if transform.startswith("clip:"):
        return np.minimum(c, float(transform.split(":")[1]))
    raise ValueError(f"Unknown transform: {transform}")


def compute_mi_footprint(gdf: pd.DataFrame, wt_seq: str, transform: str = "sqrt") -> np.ndarray:
    """
    MI between WT/mutant identity and DNA/RNA label at each position.
    Weights by sqrt-transformed counts (or other transform).
    Returns MI array of shape (L,) in bits.
    """
    wt_enc = wt_seq.encode("ascii")

    is_match = np.vstack([
        np.array(compare_string_bytes_equal(wt_enc, s.encode("ascii")))
        for s in gdf["promoter"].astype(str).values
    ]).astype(np.int64)

    n, L = is_match.shape
    x = _transform_counts(gdf["ct_0"].values, transform)   # DNA weights
    y = _transform_counts(gdf["ct_1"].values, transform)   # RNA weights

    total = np.sum(x + y)
    if total <= 0:
        return np.zeros(L)

    # Joint distribution: axis0 = WT/mut, axis1 = DNA/RNA
    joint = np.zeros((L, 2, 2), dtype=np.float64)
    joint[:, 0, 0] = is_match.T @ x     # WT  & DNA
    joint[:, 0, 1] = is_match.T @ y     # WT  & RNA
    mismatch = 1 - is_match
    joint[:, 1, 0] = mismatch.T @ x     # mut & DNA
    joint[:, 1, 1] = mismatch.T @ y     # mut & RNA
    joint /= total

    mi = np.empty(L, dtype=np.float64)
    for i in range(L):
        mi[i] = mi_from_joint_2x2(joint[i])

    return mi


# ---------------------------------------------------------------------------
# Expression shift footprint (your implementation)
# ---------------------------------------------------------------------------

def compute_expr_shift(gdf: pd.DataFrame, wt_seq: str) -> np.ndarray:
    """
    Expression shift per (position, base).
    Returns array of shape (L, 4) — bases ordered A, C, G, T.
    Lambda-normalized as in your original compute_es().
    """
    wt_enc = wt_seq.encode("ascii")

    is_mut = 1 - np.vstack([
        np.array(compare_string_bytes_equal(wt_enc, s.encode("ascii")))
        for s in gdf["promoter"].astype(str).values
    ])

    int_seq = batch_dna_to_int(gdf["promoter"].values)

    Lambda = np.median((gdf["ct_1"].values + 1) / (gdf["ct_0"].values + 1))
    relative_counts = (gdf["ct_1"].values + 1) / (gdf["ct_0"].values + 1)
    exp_diff = relative_counts - np.mean(relative_counts)

    L = is_mut.shape[1]
    ex_shift_arr = np.zeros((L, 4))
    accumulate_shifts(int_seq, is_mut, exp_diff, ex_shift_arr)
    ex_shift_arr *= (1.0 / Lambda)

    return ex_shift_arr   # (L, 4)



def es_has_outlier(es_at_peak: np.ndarray, k: float = 2.0) -> bool:
    """
    Given the 4 expression shift values at the peak position (one per base),
    return True if one mutant base is a clear outlier among the three non-WT values.

    The WT base has ES = 0 by construction (accumulate_shifts only accumulates
    over mutated positions), so we exclude it and work with the 3 mutant values.
    Criterion: max(|ES|) > k * median(|ES|) across the 3 mutant bases.
    """
    abs_es   = np.abs(es_at_peak)
    top_idx  = np.argmax(abs_es)
    # exclude the zero (WT) entry and the top, leaving 2 others — use all 3 for median
    nonzero  = abs_es[abs_es > 0]
    if len(nonzero) == 0:
        return False
    return float(abs_es[top_idx]) > k * float(np.median(nonzero))


# ---------------------------------------------------------------------------
# Score one (experiment, promoter) pair
# ---------------------------------------------------------------------------

def score_one(
    gdf: pd.DataFrame,
    wt_seq: str,
    noise_a: float,
    mi_z: float,
    es_k: float = 2.0,
    transform: str = "sqrt",
) -> dict:
    """
    Score one (experiment, promoter) dataframe for de novo activity.
    Returns a dict of scalar metrics plus MI and ES arrays for plotting.
    """
    N = len(gdf)
    if N < 20:
        return {"valid": False, "N": N}

    noise_floor = noise_a / N
    threshold   = mi_z * noise_floor

    mi = compute_mi_footprint(gdf, wt_seq, transform=transform)
    es = compute_expr_shift(gdf, wt_seq)           # (L, 4)
    peak_pos  = int(np.argmax(mi))
    peak_mi   = mi[peak_pos]
    peak_shift = np.abs(es[peak_pos])  # (4,) — one value per base

    # Background = mean MI excluding top 3 positions
    background = np.mean(np.sort(mi)[:-3])

    denovo_score  = peak_mi / noise_floor

    # De novo criteria:
    #   1. Peak is real (above noise floor)
    #   2. Background is quiet
    #   3. One base is a clear outlier in expression shift at the peak
    is_denovo = (
        peak_mi   > threshold
        and background < noise_floor
        and es_has_outlier(es[peak_pos], k=es_k)
    )

    return {
        "valid":         True,
        "N":             N,
        "noise_floor":   noise_floor,
        "threshold":     threshold,
        "peak_pos":      peak_pos,
        "peak_mi":       peak_mi,
        "peak_shift":    float(peak_shift.max()),  # max |ES| across bases at peak
        "background_mi": background,
        "denovo_score":  denovo_score,
        "is_denovo":     is_denovo,
        "mi":            mi,
        "es":            es,
    }


# ---------------------------------------------------------------------------
# Scanner
# ---------------------------------------------------------------------------

SKIP_PROMOTERS = {"galEp", "ybeDp2"}


def run_scan(
    indices: list,
    df_map: pd.DataFrame,
    wt_dict: dict,
    data_dir: str,
    noise_a: float = 8.0,
    mi_z: float = 3.0,
    es_k: float = 2.0,
    transform: str = "sqrt",
) -> pd.DataFrame:
    """
    Loop over all experiment indices and all promoters found in each.
    Returns a DataFrame sorted by de novo score (descending).
    """
    records = []

    for ind in indices:
        print(f"  {ind}", end=" ... ", flush=True)
        try:
            df_all = get_counts(ind, df_map, data_dir=data_dir)
        except FileNotFoundError as e:
            print(f"SKIP ({e})")
            continue

        promoters = [p for p in df_all["name"].unique()
                     if p not in SKIP_PROMOTERS and p in wt_dict]

        for prom in promoters:
            gdf    = df_all[df_all["name"] == prom]
            result = score_one(gdf, wt_dict[prom], noise_a, mi_z,
                               es_k, transform)
            if not result["valid"]:
                continue
            records.append({
                "experiment":        ind,
                "promoter":          prom,
                "N":                 result["N"],
                "peak_pos":          result["peak_pos"],
                "peak_mi":           result["peak_mi"],
                "noise_floor":       result["noise_floor"],
                "denovo_score":      result["denovo_score"],

                "peak_shift":        result["peak_shift"],
                "background_mi":     result["background_mi"],
                "is_denovo":         result["is_denovo"],
            })

        print(f"{len(promoters)} promoters done", flush=True)

    df_results = pd.DataFrame(records)
    if len(df_results) == 0:
        print("No valid results found.")
        return df_results

    return df_results.sort_values("denovo_score", ascending=False).reset_index(drop=True)


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_heatmap(df_results: pd.DataFrame, save_path: str = None):
    """Heatmap: rows = promoters, columns = experiments. ★ = de novo candidate."""
    pivot = df_results.pivot_table(
        index="promoter", columns="experiment", values="denovo_score", aggfunc="first"
    )
    flag = df_results.pivot_table(
        index="promoter", columns="experiment", values="is_denovo", aggfunc="first"
    )

    fig, ax = plt.subplots(figsize=(max(8, len(pivot.columns) * 0.8 + 2),
                                    max(6, len(pivot.index) * 0.35 + 2)))
    vmax = np.nanpercentile(pivot.values, 95)
    im = ax.imshow(pivot.values, aspect="auto", cmap="YlOrRd",
                   vmin=0, vmax=vmax, interpolation="none")

    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=45, ha="right", fontsize=8)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index, fontsize=7)
    ax.set_xlabel("Experiment")
    ax.set_ylabel("Promoter")
    ax.set_title("De novo score (peak MI / noise floor) — ★ = candidate", fontsize=11)

    for i, prom in enumerate(pivot.index):
        for j, exp in enumerate(pivot.columns):
            try:
                if flag.loc[prom, exp]:
                    ax.text(j, i, "★", ha="center", va="center",
                            fontsize=9, color="black", fontweight="bold")
            except KeyError:
                pass

    plt.colorbar(im, ax=ax, label="De novo score (× noise floor)", shrink=0.6)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Saved heatmap → {save_path}")
    else:
        plt.show()


def plot_candidate_footprints(
    candidates: pd.DataFrame,
    df_map: pd.DataFrame,
    wt_dict: dict,
    data_dir: str,
    noise_a: float,
    mi_z: float,
    es_k: float = 2.0,
    transform: str = "sqrt",
    save_path: str = None,
    max_plots: int = 24,
):
    """MI footprint (top) and expression shift (bottom) for each candidate."""
    n = min(len(candidates), max_plots)
    if n == 0:
        return

    ncols  = 3
    nrows  = int(np.ceil(n / ncols))
    fig, axes = plt.subplots(
        nrows * 2, ncols,
        figsize=(ncols * 5, nrows * 4),
        gridspec_kw={"hspace": 0.05, "wspace": 0.3},
    )
    # Ensure axes is always 2D
    if nrows * 2 == 1:
        axes = axes[np.newaxis, :]

    BASE_COLORS = ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3"]  # A C G T

    for idx, (_, row) in enumerate(candidates.head(n).iterrows()):
        col    = idx % ncols
        row_mi = (idx // ncols) * 2
        row_es = row_mi + 1

        try:
            df_all = get_counts(row["experiment"], df_map, data_dir=data_dir)
            gdf    = df_all[df_all["name"] == row["promoter"]]
            result = score_one(gdf, wt_dict[row["promoter"]],
                               noise_a, mi_z, es_k, transform)
        except Exception:
            continue

        mi  = result["mi"]
        es  = result["es"]
        pos = np.arange(len(mi))

        # --- MI panel ---
        ax = axes[row_mi, col]
        ax.bar(pos, mi, color="steelblue", alpha=0.8, width=1.0)
        ax.axhline(result["threshold"], color="red", lw=1.2, linestyle="--")
        ax.axvline(result["peak_pos"],  color="orange", lw=2, alpha=0.9)
        ax.set_title(
            f'{row["promoter"]}  exp={row["experiment"]}\n'
            f'score={row["denovo_score"]:.1f}×  pos={row["peak_pos"]}',
            fontsize=7,
        )
        ax.set_ylabel("MI (bits)", fontsize=6)
        ax.tick_params(labelsize=5)
        ax.set_xticks([])

        # --- ES panel ---
        ax2 = axes[row_es, col]
        for b, (c, label) in enumerate(zip(BASE_COLORS, "ACGT")):
            ax2.bar(pos, es[:, b], color=c, alpha=0.65, width=1.0, label=label)
        ax2.axhline(0, color="black", lw=0.5)
        ax2.axvline(result["peak_pos"], color="orange", lw=2, alpha=0.9)
        ax2.set_ylabel("Expr shift", fontsize=6)
        ax2.set_xlabel("Position", fontsize=6)
        ax2.tick_params(labelsize=5)
        if idx == 0:
            ax2.legend(fontsize=5, ncol=4, loc="upper right")

    # Hide unused panels
    for idx in range(n, nrows * ncols):
        col    = idx % ncols
        row_mi = (idx // ncols) * 2
        axes[row_mi,     col].set_visible(False)
        axes[row_mi + 1, col].set_visible(False)

    fig.suptitle(
        "De novo candidates — MI footprint (top) & expression shift (bottom)",
        fontsize=11, y=1.01,
    )
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Saved candidate footprints → {save_path}")
    else:
        plt.show()


# ---------------------------------------------------------------------------
# Save all outputs
# ---------------------------------------------------------------------------

def save_outputs(
    df_results: pd.DataFrame,
    indices: list,
    df_map: pd.DataFrame,
    wt_dict: dict,
    data_dir: str,
    noise_a: float = 8.0,
    mi_z: float = 3.0,
    es_k: float = 2.0,
    transform: str = "sqrt",
    output_dir: str = ".",
) -> pd.DataFrame:
    """Write results.csv, candidates.csv, heatmap.png, candidate_footprints.png."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    df_results.to_csv(out / "results.csv", index=False)
    print(f"Saved {len(df_results)} results → {out / 'results.csv'}")

    candidates = df_results[df_results["is_denovo"]].copy()
    candidates.to_csv(out / "candidates.csv", index=False)
    print(f"De novo candidates: {len(candidates)}")
    if len(candidates) > 0:
        print(candidates[["experiment", "promoter", "peak_pos",
                           "denovo_score", "peak_shift"]].to_string(index=False))

    plot_heatmap(df_results, save_path=str(out / "heatmap.png"))

    if len(candidates) > 0:
        plot_candidate_footprints(
            candidates, df_map, wt_dict,
            data_dir=data_dir,
            noise_a=noise_a, mi_z=mi_z,
            es_k=es_k,
            transform=transform,
            save_path=str(out / "candidate_footprints.png"),
        )

    return candidates